# Generated by Django 5.1.5 on 2026-08-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('writer', models.CharField(blank=True, max_length=255)),
                ('production_company', models.CharField(blank=True, max_length=255)),
                ('distributor', models.CharField(blank=True, max_length=255)),
                ('actors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['title', 'release_year'],
                'indexes': [models.Index(fields=['release_year', 'title'], name='films_film_release_5eb75c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(blank=True, max_length=512)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_mappable', models.BooleanField(db_index=True, default=False)),
                ('neighborhood', models.CharField(blank=True, db_index=True, max_length=255)),
                ('supervisor_district', models.CharField(blank=True, max_length=16)),
                ('fun_facts', models.TextField(blank=True)),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('data_as_of', models.DateTimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='films.film')),
            ],
            options={
                'ordering': ['film__title', 'location_text'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='films_filml_latitud_fe56f9_idx'), models.Index(fields=['is_mappable', 'neighborhood'], name='films_filml_is_mapp_01a6cf_idx')],
            },
        ),
    ]
